//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT2_PhanLacViet_2210900079_project2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTDH
    {
        public int STT { get; set; }
        public string MaDH { get; set; }
        public string MaSp { get; set; }
        public string TenSP { get; set; }
        public Nullable<int> GiaCa { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
